### ISSUE TITLE
Docs for graph visualization

### ISSUE THREAD

**Issue by himoto** [biomass-dev/biomass#145]
**TODO:**
- [x] Edit [`graph_visualization.rst`](https://github.com/biomass-dev/biomass/blob/doc-graphviz/docs/graph_visualization.rst)
- [x] Use one of biomass.models for showing usage examples
- [x] Add how to use `dynamic/static_plot()`

Note:
If you want embed images, please put the source in `_static/img/` folder. You can call them via `.. image:: _static/img/xxx` in .rst files.
